#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DiscreteSeekBarDemo.Resource", IsApplication=true)]

namespace DiscreteSeekBarDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int discreteSeekBarStyle = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int dsb_allowTrackClickToDrag = 2130771973;
			
			// aapt resource value: 0x7f010009
			public const int dsb_indicatorColor = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int dsb_indicatorElevation = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int dsb_indicatorFormatter = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public const int dsb_indicatorPopupEnabled = 2130771981;
			
			// aapt resource value: 0x7f010008
			public const int dsb_indicatorTextAppearance = 2130771976;
			
			// aapt resource value: 0x7f010002
			public const int dsb_max = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int dsb_min = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int dsb_mirrorForRtl = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int dsb_progressColor = 2130771974;
			
			// aapt resource value: 0x7f01000c
			public const int dsb_rippleColor = 2130771980;
			
			// aapt resource value: 0x7f010007
			public const int dsb_trackColor = 2130771975;
			
			// aapt resource value: 0x7f010003
			public const int dsb_value = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int dsb_disabled_color = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int dsb_progress_color = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int dsb_progress_color_list = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int dsb_ripple_color_focused = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int dsb_ripple_color_list = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int dsb_ripple_color_pressed = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int dsb_track_color = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int dsb_track_color_list = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int my_floater_color = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int my_progress_color = 2130968585;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int discrete1 = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int discrete2 = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int discrete3 = 2131230722;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int lorem_ipsum = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int lorem_ipsum_2 = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int AppTheme = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int CustomFloaterTextAppearance = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int Widget_DiscreteIndicatorTextAppearance = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Widget_DiscreteSeekBar = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] DiscreteSeekBar = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 4
			public const int DiscreteSeekBar_dsb_allowTrackClickToDrag = 4;
			
			// aapt resource value: 8
			public const int DiscreteSeekBar_dsb_indicatorColor = 8;
			
			// aapt resource value: 9
			public const int DiscreteSeekBar_dsb_indicatorElevation = 9;
			
			// aapt resource value: 10
			public const int DiscreteSeekBar_dsb_indicatorFormatter = 10;
			
			// aapt resource value: 12
			public const int DiscreteSeekBar_dsb_indicatorPopupEnabled = 12;
			
			// aapt resource value: 7
			public const int DiscreteSeekBar_dsb_indicatorTextAppearance = 7;
			
			// aapt resource value: 1
			public const int DiscreteSeekBar_dsb_max = 1;
			
			// aapt resource value: 0
			public const int DiscreteSeekBar_dsb_min = 0;
			
			// aapt resource value: 3
			public const int DiscreteSeekBar_dsb_mirrorForRtl = 3;
			
			// aapt resource value: 5
			public const int DiscreteSeekBar_dsb_progressColor = 5;
			
			// aapt resource value: 11
			public const int DiscreteSeekBar_dsb_rippleColor = 11;
			
			// aapt resource value: 6
			public const int DiscreteSeekBar_dsb_trackColor = 6;
			
			// aapt resource value: 2
			public const int DiscreteSeekBar_dsb_value = 2;
			
			public static int[] Theme = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int Theme_discreteSeekBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
